### ISSUE TITLE
Seems like nothing happened.

### ISSUE THREAD

**Issue by oleksiy-nesterov** [SnowLew/react-native-screenshot-prevention#2]
The video recording and the taking snapshot work as usual. Tested on IOS  15, iPhone XR

`  
public componentDidMount() {
        preventScreenCapture();
  }

  public componentWillUnmount() {
        allowScreenCapture();
  }
  
  `

**Comment by oleksiy-nesterov** [comment]
Oh, found comments

// Enable screenshot (android only)
allowScreenCapture()

//Disable screenshot (android only)
preventScreenCapture()

is that possible? to have the same behavior on IOS?

**Comment by goul4rt** [comment]
Its possible, but using some payed frameworks (I think)
something like that:

https://screenshieldkit.com/

**Comment by goul4rt** [comment]
Have some possibilities
Possibilities might include creating a `white` layer on top of all views, but I don't know if that's the most efficient approach.

**Comment by goul4rt** [comment]
I will add the request to the list of upcoming lib updates.
