### ISSUE TITLE
Error ios

### ISSUE THREAD

**Issue by EnettyTech** [SnowLew/react-native-screenshot-prevention#3]
When will there be a new update?
Android is still working fine, but for iOS, while `enableSecureView` works, I can't turn it off with `disableSecureView`. I've checked in the native code, and you've commented out this function. 
`addListener` also isn't working.
<img width="1017" alt="Screen Shot 2023-02-16 at 10 20 47" src="https://user-images.githubusercontent.com/28125294/219259926-313613c8-c484-4a35-8c13-6c4219104eff.png">
![simulator_screenshot_77F1D858-FE71-4905-AE56-C4A87B614679](https://user-images.githubusercontent.com/28125294/219259949-27b0d5ad-1620-4630-8c7e-a7497c16539c.png)

**Comment by SnowLew** [comment]
Hey o/
Thank for the comment, Ill upload an fix to it tomorrow
